"""Automated remediation: plan actions, generate patches, build templates."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, auto
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._classify import ClassificationVerdict
    from ._copilot import CopilotSession


class RemediationAction(Enum):
    PATCH = auto()
    SUGGESTION = auto()
    ISSUE_TEMPLATE = auto()
    NARRATIVE = auto()


@dataclass
class RemediationEntry:
    test_id: str
    label: str
    confidence: float
    action: RemediationAction
    content: str


@dataclass
class RemediationPlan:
    entries: list[RemediationEntry]
    patch_generated: bool


PATCH_PROMPT = """Based on the following failure analysis, generate a unified diff
patch to fix the issue. Output ONLY the patch in unified diff format.

Failure classification: {label} (confidence: {confidence})
Reasoning: {reasoning_trace}

The patch must be applicable with `git apply` and include context lines.
Do NOT include explanations — only the diff."""

INFRA_ISSUE_TEMPLATE = """---
title: "[glitch] Infrastructure failure detected — {test_id}"
labels: ["bug", "infrastructure", "auto-generated"]
---

## Failure Summary

{reasoning_trace}

## Recommended Actions

1. Check runner health and resource availability
2. Verify Kubernetes cluster state
3. Inspect Ceph/LXD for anomalies

## Evidence

{evidence_summary}

---
_Generated by glitch analyze on {timestamp}_
"""

ENV_ISSUE_TEMPLATE = """---
title: "[glitch] Environment failure detected — {test_id}"
labels: ["bug", "environment", "auto-generated"]
---

## Failure Summary

{reasoning_trace}

## Recommended Actions

1. Check external dependency availability (network, registry, package sources)
2. Verify upstream service health
3. Retry with increased timeouts or retry limits

## Evidence

{evidence_summary}

---
_Generated by glitch analyze on {timestamp}_
"""


def plan_remediation(
    verdicts: list[ClassificationVerdict],
    threshold: float,
) -> RemediationPlan:
    entries: list[RemediationEntry] = []

    for verdict in verdicts:
        for label, confidence in verdict.labels.items():
            if label in ("charm-bug", "test-bug"):
                action = (
                    RemediationAction.PATCH
                    if confidence >= threshold
                    else RemediationAction.SUGGESTION
                )
            elif label == "flaky":
                action = RemediationAction.SUGGESTION
            elif label in ("infrastructure", "environment"):
                action = RemediationAction.ISSUE_TEMPLATE
            else:
                action = RemediationAction.NARRATIVE

            entries.append(
                RemediationEntry(
                    test_id=verdict.test_id,
                    label=label,
                    confidence=confidence,
                    action=action,
                    content="",
                )
            )

    patch_generated = any(e.action == RemediationAction.PATCH for e in entries)

    return RemediationPlan(entries=entries, patch_generated=patch_generated)


def generate_patch(
    plan: RemediationPlan,
    session: CopilotSession,
    verdicts: list[ClassificationVerdict],
) -> None:
    candidates = [
        e
        for e in plan.entries
        if e.action == RemediationAction.PATCH
    ]
    if not candidates:
        return

    candidate = max(candidates, key=lambda e: e.confidence)
    verdict = next(
        (v for v in verdicts if v.test_id == candidate.test_id),
        None,
    )
    reasoning = verdict.reasoning_trace if verdict else ""
    prompt = PATCH_PROMPT.format(
        label=candidate.label,
        confidence=candidate.confidence,
        reasoning_trace=reasoning,
    )
    candidate.content = session.classify(prompt)


def generate_content(
    plan: RemediationPlan,
    session: CopilotSession,
    verdicts: list[ClassificationVerdict],
    evidence_summary: str,
) -> None:
    from datetime import datetime, timezone

    verdict_map = {
        v.test_id: v for v in verdicts
    }

    generate_patch(plan, session, verdicts)

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    for entry in plan.entries:
        verdict = verdict_map.get(entry.test_id)
        reasoning = verdict.reasoning_trace if verdict else ""

        if entry.action == RemediationAction.SUGGESTION:
            if entry.label in ("charm-bug", "test-bug"):
                suggestion_prompt = (
                    f"Based on this failure analysis for {entry.test_id} "
                    f"({entry.label}, confidence {entry.confidence}), "
                    f"suggest a potential fix in prose form. "
                    f"Confidence is below remediation threshold so no patch will be generated.\n\n"
                    f"Reasoning: {reasoning}"
                )
                entry.content = session.classify(suggestion_prompt)
            elif entry.label == "flaky":
                suggestion_prompt = (
                    f"Based on this failure analysis for {entry.test_id} "
                    f"({entry.label}, confidence {entry.confidence}), "
                    f"suggest retry policies, test isolation changes, or ordering "
                    f"guards in prose form.\n\n"
                    f"Reasoning: {reasoning}"
                )
                entry.content = session.classify(suggestion_prompt)
            else:
                entry.content = (
                    f"Suggested fix for {entry.test_id} ({entry.label}, "
                    f"confidence {entry.confidence}):\n\n{reasoning}"
                )

        elif entry.action == RemediationAction.ISSUE_TEMPLATE:
            template = (
                INFRA_ISSUE_TEMPLATE
                if entry.label == "infrastructure"
                else ENV_ISSUE_TEMPLATE
            )
            entry.content = template.format(
                test_id=entry.test_id,
                reasoning_trace=reasoning,
                evidence_summary=evidence_summary,
                timestamp=timestamp,
            )

        elif entry.action == RemediationAction.NARRATIVE:
            entry.content = (
                f"## {entry.test_id} — {entry.label}\n\n"
                f"Confidence: {entry.confidence}\n\n"
                f"Insufficient signal to classify with confidence. "
                f"Additional telemetry or investigation is needed.\n\n"
                f"Reasoning:\n{reasoning}"
            )
